### ISSUE TITLE
Add hint for key binding

### ISSUE THREAD

**Issue by lebensterben** [arcolinux/arcolinux-logout#10]
Could you add some hints for keybindings?

One possibility is to add an underline or apply a different color to the character bound to a shortcut key.
For example, the default keybinding in pango syntax would be

```xml
<span>
    loc<u>k</u>
</span>
<span>
    <u>s</u>hutdown
</span>
<span>
    <u>r</u>estart
</span>
<span>
    s<u>u</u>spand
</span>
<span>
    <u>l</u>ogout
</span>
```

**Comment by arcolinuxz** [comment]
done
