### ISSUE TITLE
unable to logout from I3, package is missing

### ISSUE THREAD

**Issue by mario-almeida** [arcolinux/arcolinux-logout#15]
==> Proceed with install? [Y/n] y
:: (1/1) Parsing SRCINFO: arcolinux-logout
==> Making package: arcolinux-logout 22.03_01-2 (Sat 07 May 2022 08:22:17 PM +04)
==> Retrieving sources...
  -> Downloading arcolinux-logout-22.03_01.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 3012k    0 3012k    0     0  1287k      0 --:--:--  0:00:02 --:--:-- 2610k
==> Validating source files with md5sums...
    arcolinux-logout-22.03_01.tar.gz ... FAILED
==> ERROR: One or more files did not pass the validity check!
 -> error downloading sources: arcolinux-logout
	 context: exit status 1
	

==> Making package: arcolinux-logout 22.03_01-2 (Sat 07 May 2022 08:22:20 PM +04)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found arcolinux-logout-22.03_01.tar.gz
==> Validating source files with md5sums...
    arcolinux-logout-22.03_01.tar.gz ... FAILED
==> ERROR: One or more files did not pass the validity check!
 -> error making: arcolinux-logout

**Comment by arcolinuxz** [comment]
watch our info on discord
watch our info on youtube
this is not the place
