### ISSUE TITLE
Bindings configured with .config/archlinux-logout/archlinux-logout.conf are not respected

### ISSUE THREAD

**Issue by korbajan** [arcolinux/arcolinux-logout#17]
It would be great to use bindings configured via user's archlinux-logout configuration.

**Comment by arcolinuxz** [comment]
Please test out the package that is now online
it has your changes in them

archlinux-logout-dev-git and let me know if it works as it is supposed to

**Comment by arcolinuxz** [comment]
as I understand it is NOT using the /etc/ configuration file which is at it should  be
when there is no user config present one is created anyway
we should not encourage users to meddle in the /etc folder 

if there is code in there that affects the /etc file we better remove it
what do you think?

**Comment by korbajan** [comment]
Yes, It is working fine.

All this patch does is to actually use already retrieved settings (configuration) for binds from user's config (which if does not exists is created by copying the one from /etc - but that is existing behaviour). So there is no impact on any config file at all :)

**Comment by korbajan** [comment]
Thanks for merging. So this one can be closed. And btw - there was already an old issue for that: https://github.com/arcolinux/archlinux-logout/issues/11.
