### ISSUE TITLE
No module named 'cairo'

### ISSUE THREAD

**Issue by olaioo** [arcolinux/arcolinux-logout#6]
I tried to use the alternative to oblogout, and I got this error:

> Traceback (most recent call last):
  File "/usr/lib/arcologout/arcologout.py", line 5, in <module>
    import cairo
ModuleNotFoundError: No module named 'cairo'

I've tried to install it over the pacman and pip, but nothing worked. So, I'm here to ask for ideas.

**Comment by arcolinuxz** [comment]
not used anymore
not maintained anymore

**Comment by olaioo** [comment]
Right, but is there an alternative to arcolinux-logout?

I'm using xmonad, so I would like to have some interface to restart, shutdown, etc..

**Comment by olaioo** [comment]
I'm closing the issue. After I uninstall Anaconda I was able to execute the package arcolinux-logout. Probably, the Anaconda was causing the error "No module named 'cairo'".
