### ISSUE TITLE
arcolinux-logout Button/Function not working

### ISSUE THREAD

**Issue by Kjvthomas** [arcolinux/arcolinux-logout#8]
running arcolinuxb
The Logout Button itself does not work. When i run from terminal I get this error:

arcolinux-logout
Your desktop is Xmonad
Traceback (most recent call last):
  File "/usr/share/arcologout/arcologout.py", line 255, in on_click
    self.click_button(widget, data)
  File "/usr/share/arcologout/arcologout.py", line 284, in click_button
    self.exec_cmd(command)
  File "/usr/share/arcologout/arcologout.py", line 345, in exec_cmd
    fn.os.system(cmdline)
TypeError: expected str, bytes or os.PathLike object, not NoneType

Lock screen works, reboot, and shutdown work, just the logout function does not work.

I am using LXDM for the login manager.

also the logout function works in default settings awesome, and in default settings i3, however with default settings openbox, it does not work as well

I also tried a brand new xmonad config, by reinstalling xmonad from the tweak tool, to rule out if anything I changed in Xmonad was the issue, i recompiled, restarted, and rebooted, and the error still happens, same error messages.

I did install LXDM prior to all these errors. I also installed ArcoLinux B with NO packages selected, Booted into it, Logout works fine. I installed LXDM, and BOOM I get the error, where logout does not work. So I believe it is an issue with LXDM and xmonad

**Comment by arcolinuxz** [comment]
This is where the code is.

https://github.com/arcolinux/arcolinux-logout/blob/b6ed626dc9d3e145dd09c34dee9bf56f89699050/usr/share/arcologout/Functions.py#L133

worked fine with sddm

check the files on your system.

**Comment by arcolinuxz** [comment]
it is a bit higher
LXDM calls it Xmonad and not xmonad
X and x matters in Linux
will add a line to the app

**Comment by arcolinuxz** [comment]
Solved
